In [1]:
import pandas as pd
import numpy as np

In [2]:
URL = 'https://raw.githubusercontent.com/aviralb13/git-codes/main/datas/brainstroke.csv'
data = pd.read_csv(URL)
data.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1

In [15]:
one_hot = pd.get_dummies(data['gender'])
data = data.drop('gender',axis = 1)
data = data.join(one_hot)

one_hot = pd.get_dummies(data['work_type'])
data = data.drop('work_type',axis = 1)
data = data.join(one_hot)

from sklearn import preprocessing

label = preprocessing.LabelEncoder()
data['ever_married'] = label.fit_transform(data['ever_married'])

data.head()

KeyError: 'gender'

In [ ]:
data['smoking_status'].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],
      dtype=object)

In [ ]:
'''import category_encoders

work_Mapping = [{'col':'work_type','mapping':{'Self-employed':0,'children':,'Private':1,}}]

work_encoder = category_encoders.OrdinalEncoder(mapping = work_Mapping, return_df = True) 

data['work_type'] = work_encoder.fit_transform(data['work_type'])'''

"import category_encoders\n\nwork_Mapping = [{'col':'work_type','mapping':{'Self-employed':0,'children':,'Private':1,}}]\n\nwork_encoder = category_encoders.OrdinalEncoder(mapping = work_Mapping, return_df = True) \n\ndata['work_type'] = work_encoder.fit_transform(data['work_type'])"

In [ ]:
import category_encoders

Residence_Mapping = [{'col':'Residence_type','mapping':{'Urban':0,'Rural':1}}]
smoke_Mapping = [{'col':'smoking_status','mapping':{'formerly smoked':1,'never smoked':2, 'smokes':0, 'Unknown':-1}}]

Residence_encoder = category_encoders.OrdinalEncoder(mapping = Residence_Mapping, return_df = True) 
smoke_encoder = category_encoders.OrdinalEncoder(mapping = smoke_Mapping, return_df = True) 

data['Residence_type'] = Residence_encoder.fit_transform(data['Residence_type'])
data['smoking_status'] = smoke_encoder.fit_transform(data['smoking_status'])

In [ ]:
data.head()

,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Female,Male,Govt_job,Private,Self-employed,children
0,67.0,0,1,1,0,228.69,36.6,1,1,0,1,0,1,0,0
1,80.0,0,1,1,1,105.92,32.5,2,1,0,1,0,1,0,0
2,49.0,0,0,1,0,171.23,34.4,0,1,1,0,0,1,0,0
3,79.0,1,0,1,1,174.12,24.0,2,1,1,0,0,0,1,0
4,81.0,0,0,1,0,186.21,29.0,1,1,0,1,0,1,0,0

In [ ]:
features = ['age', 'hypertension', 'heart_disease', 'ever_married','Residence_type', 'avg_glucose_level', 'bmi', 'smoking_status','Female', 'Male', 'Govt_job', 'Private', 'Self-employed','children']
x = data[features]
y = data['stroke']

In [ ]:
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y = train_test_split(x,y)

In [ ]:
from lazypredict.Supervised import LazyClassifier

model = LazyClassifier()
models, predictions = model.fit(train_x,test_x,train_y,test_y)
models.head(60)

                                0  \
0               AdaBoostRegressor
1                BaggingRegressor
2                   BayesianRidge
3           DecisionTreeRegressor
4                  DummyRegressor
5                      ElasticNet
6                    ElasticNetCV
7              ExtraTreeRegressor
8             ExtraTreesRegressor
9                  GammaRegressor
10       GaussianProcessRegressor
11      GradientBoostingRegressor
12  HistGradientBoostingRegressor
13                 HuberRegressor
14            KNeighborsRegressor
15                    KernelRidge
16                           Lars
17                         LarsCV
18                          Lasso
19                        LassoCV
20                      LassoLars
21                    LassoLarsCV
22                    LassoLarsIC
23               LinearRegression
24                      LinearSVR
25                   MLPRegressor
26                          NuSVR
27      OrthogonalMatchingPursuit
28    OrthogonalMatchingPursuitCV
29     PassiveAggressiveRegressor
30               PoissonRegressor
31              QuantileRegressor
32                RANSACRegressor
33          RandomForestRegressor
34                          Ridge
35                        RidgeCV
36                   SGDRegressor
37                            SVR
38              StackingRegressor
39     TransformedTargetRegressor
40               TweedieRegressor
41                   XGBRegressor
42                  LGBMRegressor

                                                    1
0   <class 'sklearn.ensemble._weight_boosting.AdaB...
1   <class 'sklearn.ensemble._bagging.BaggingRegre...
2   <class 'sklearn.linear_model._bayes.BayesianRi...
3   <class 'sklearn.tree._classes.DecisionTreeRegr...
4              <class 'sklearn.dummy.DummyRegressor'>
5   <class 'sklearn.linear_model._coordinate_desce...
6   <class 'sklearn.linear_model._coordinate_desce...
7   <class 'sklearn.tree._classes.ExtraTreeRegress...
8   <class 'sklearn.ensemble._forest.ExtraTreesReg...
9   <class 'sklearn.linear_model._glm.glm.GammaReg...
10  <class 'sklearn.gaussian_process._gpr.Gaussian...
11  <class 'sklearn.ensemble._gb.GradientBoostingR...
12  <class 'sklearn.ensemble._hist_gradient_boosti...
13  <class 'sklearn.linear_model._huber.HuberRegre...
14  <class 'sklearn.neighbors._regression.KNeighbo...
15         <class 'sklearn.kernel_ridge.KernelRidge'>
16   <class 'sklearn.linear_model._least_angle.Lars'>
17  <class 'sklearn.linear_model._least_angle.Lars...
18  <class 'sklearn.linear_model._coordinate_desce...
19  <class 'sklearn.linear_model._coordinate_desce...
20  <class 'sklearn.linear_model._least_angle.Lass...
21  <class 'sklearn.linear_model._least_angle.Lass...
22  <class 'sklearn.linear_model._least_angle.Lass...
23  <class 'sklearn.linear_model._base.LinearRegre...
24           <class 'sklearn.svm._classes.LinearSVR'>
25  <class 'sklearn.neural_network._multilayer_per...
26               <class 'sklearn.svm._classes.NuSVR'>
27  <class 'sklearn.linear_model._omp.OrthogonalMa...
28  <class 'sklearn.linear_model._omp.OrthogonalMa...
29  <class 'sklearn.linear_model._passive_aggressi...
30  <class 'sklearn.linear_model._glm.glm.PoissonR...
31  <class 'sklearn.linear_model._quantile.Quantil...
32  <class 'sklearn.linear_model._ransac.RANSACReg...
33  <class 'sklearn.ensemble._forest.RandomForestR...
34        <class 'sklearn.linear_model._ridge.Ridge'>
35      <class 'sklearn.linear_model._ridge.RidgeCV'>
36  <class 'sklearn.linear_model._stochastic_gradi...
37                 <class 'sklearn.svm._classes.SVR'>
38  <class 'sklearn.ensemble._stacking.StackingReg...
39  <class 'sklearn.compose._target.TransformedTar...
40  <class 'sklearn.linear_model._glm.glm.TweedieR...
41             <class 'xgboost.sklearn.XGBRegressor'>
42           <class 'lightgbm.sklearn.LGBMRegressor'>
('BaggingRegressor', <class 'sklearn.ensemble._bagging.BaggingRegressor'>)

100%|██████████| 29/29 [00:03<00:00,  7.93it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
NearestCentroid,0.76,0.72,0.72,0.83,0.01
GaussianNB,0.86,0.66,0.66,0.89,0.01
QuadraticDiscriminantAnalysis,0.88,0.64,0.64,0.90,0.01
Perceptron,0.82,0.62,0.62,0.86,0.01
ExtraTreeClassifier,0.91,0.58,0.58,0.91,0.01
DecisionTreeClassifier,0.91,0.57,0.57,0.91,0.04
LabelSpreading,0.92,0.56,0.56,0.92,0.33
LabelPropagation,0.92,0.56,0.56,0.91,0.26
LGBMClassifier,0.94,0.51,0.51,0.92,1.18
KNeighborsClassifier,0.94,0.51,0.51,0.92,0.03
BernoulliNB,0.94,0.51,0.51,0.92,0.01
ExtraTreesClassifier,0.94,0.51,0.51,0.92,0.20
XGBClassifier,0.94,0.50,0.50,0.92,0.48
LinearDiscriminantAnalysis,0.94,0.50,0.50,0.92,0.02
SVC,0.95,0.50,0.50,0.92,0.14
SGDClassifier,0.95,0.50,0.50,0.92,0.02
RidgeClassifierCV,0.95,0.50,0.50,0.92,0.04
RidgeClassifier,0.95,0.50,0.50,0.92,0.04
LinearSVC,0.95,0.50,0.50,0.92,0.12
LogisticRegression,0.95,0.50,0.50,0.92,0.03
DummyClassifier,0.95,0.50,0.50,0.92,0.03
CalibratedClassifierCV,0.95,0.50,0.50,0.92,0.28
PassiveAggressiveClassifier,0.95,0.50,0.50,0.92,0.01
AdaBoostClassifier,0.95,0.50,0.50,0.92,0.09
RandomForestClassifier,0.94,0.50,0.50,0.92,0.22
BaggingClassifier,0.94,0.49,0.49,0.92,0.04

In [ ]:
from sklearn.ensemble import RandomForestClassifier
regressor_model = RandomForestClassifier()
regressor_model.fit(train_x,train_y)

RandomForestClassifier()

In [ ]:
predictions = regressor_model.predict(test_x)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(test_y, predictions)

0.9462279293739968