In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/aviralb13/git-codes/main/datas/brainstroke.csv')
data.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1

In [3]:
one_hot = pd.get_dummies(data['gender'])
data = data.drop('gender',axis = 1)
data = data.join(one_hot)

one_hot = pd.get_dummies(data['work_type'])
data = data.drop('work_type',axis = 1)
data = data.join(one_hot)

data.head()

,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Female,Male,Govt_job,Private,Self-employed,children
0,67.0,0,1,Yes,Urban,228.69,36.6,formerly smoked,1,0,1,0,1,0,0
1,80.0,0,1,Yes,Rural,105.92,32.5,never smoked,1,0,1,0,1,0,0
2,49.0,0,0,Yes,Urban,171.23,34.4,smokes,1,1,0,0,1,0,0
3,79.0,1,0,Yes,Rural,174.12,24.0,never smoked,1,1,0,0,0,1,0
4,81.0,0,0,Yes,Urban,186.21,29.0,formerly smoked,1,0,1,0,1,0,0

In [4]:
from sklearn import preprocessing

label = preprocessing.LabelEncoder()
data['ever_married'] = label.fit_transform(data['ever_married'])
data.head()

,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Female,Male,Govt_job,Private,Self-employed,children
0,67.0,0,1,1,Urban,228.69,36.6,formerly smoked,1,0,1,0,1,0,0
1,80.0,0,1,1,Rural,105.92,32.5,never smoked,1,0,1,0,1,0,0
2,49.0,0,0,1,Urban,171.23,34.4,smokes,1,1,0,0,1,0,0
3,79.0,1,0,1,Rural,174.12,24.0,never smoked,1,1,0,0,0,1,0
4,81.0,0,0,1,Urban,186.21,29.0,formerly smoked,1,0,1,0,1,0,0

In [5]:
data['smoking_status'].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],
      dtype=object)

In [6]:
'''import category_encoders

work_Mapping = [{'col':'work_type','mapping':{'Self-employed':0,'children':,'Private':1,}}]

work_encoder = category_encoders.OrdinalEncoder(mapping = work_Mapping, return_df = True) 

data['work_type'] = work_encoder.fit_transform(data['work_type'])'''

"import category_encoders\n\nwork_Mapping = [{'col':'work_type','mapping':{'Self-employed':0,'children':,'Private':1,}}]\n\nwork_encoder = category_encoders.OrdinalEncoder(mapping = work_Mapping, return_df = True) \n\ndata['work_type'] = work_encoder.fit_transform(data['work_type'])"

In [ ]:
import category_encoders

Residence_Mapping = [{'col':'Residence_type','mapping':{'Urban':0,'Rural':1}}]
smoke_Mapping = [{'col':'smoking_status','mapping':{'formerly smoked':1,'never smoked':2, 'smokes':0, 'Unknown':-1}}]

Residence_encoder = category_encoders.OrdinalEncoder(mapping = Residence_Mapping, return_df = True) 
smoke_encoder = category_encoders.OrdinalEncoder(mapping = smoke_Mapping, return_df = True) 

data['Residence_type'] = Residence_encoder.fit_transform(data['Residence_type'])
data['smoking_status'] = smoke_encoder.fit_transform(data['smoking_status'])

In [ ]:
data.head()

,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Female,Male,Govt_job,Private,Self-employed,children
0,67.00,0,1,1,0,228.69,36.60,1,1,0,1,0,1,0,0
1,80.00,0,1,1,1,105.92,32.50,2,1,0,1,0,1,0,0
2,49.00,0,0,1,0,171.23,34.40,0,1,1,0,0,1,0,0
3,79.00,1,0,1,1,174.12,24.00,2,1,1,0,0,0,1,0
4,81.00,0,0,1,0,186.21,29.00,1,1,0,1,0,1,0,0

In [ ]:
features = ['age', 'hypertension', 'heart_disease', 'ever_married','Residence_type', 'avg_glucose_level', 'bmi', 'smoking_status','Female', 'Male', 'Govt_job', 'Private', 'Self-employed','children']
x = data[features]
y = data['stroke']

In [ ]:
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y = train_test_split(x,y)

In [ ]:
from lazypredict.Supervised import LazyClassifier

model = LazyClassifier()
models, predictions = model.fit(train_x,test_x,train_y,test_y)
models.head(60)

100%|██████████| 29/29 [00:05<00:00,  5.51it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
NearestCentroid,0.75,0.76,0.76,0.82,0.01
PassiveAggressiveClassifier,0.84,0.68,0.68,0.88,0.01
GaussianNB,0.86,0.68,0.68,0.89,0.01
QuadraticDiscriminantAnalysis,0.88,0.67,0.67,0.90,0.01
Perceptron,0.79,0.61,0.61,0.85,0.01
ExtraTreeClassifier,0.92,0.57,0.57,0.92,0.01
LabelPropagation,0.94,0.57,0.57,0.93,0.22
LabelSpreading,0.94,0.56,0.56,0.93,0.28
DecisionTreeClassifier,0.91,0.54,0.54,0.92,0.02
BernoulliNB,0.94,0.52,0.52,0.93,0.01
LinearDiscriminantAnalysis,0.95,0.52,0.52,0.93,0.03
LGBMClassifier,0.95,0.52,0.52,0.93,2.54
ExtraTreesClassifier,0.95,0.51,0.51,0.93,0.17
BaggingClassifier,0.95,0.51,0.51,0.93,0.04
RidgeClassifier,0.95,0.50,0.50,0.93,0.01
SGDClassifier,0.95,0.50,0.50,0.93,0.01
SVC,0.95,0.50,0.50,0.93,0.14
RidgeClassifierCV,0.95,0.50,0.50,0.93,0.02
LinearSVC,0.95,0.50,0.50,0.93,0.11
LogisticRegression,0.95,0.50,0.50,0.93,0.06
DummyClassifier,0.95,0.50,0.50,0.93,0.01
CalibratedClassifierCV,0.95,0.50,0.50,0.93,0.30
RandomForestClassifier,0.95,0.50,0.50,0.93,0.24
AdaBoostClassifier,0.95,0.50,0.50,0.93,0.08
KNeighborsClassifier,0.95,0.50,0.50,0.93,0.05
XGBClassifier,0.94,0.50,0.50,0.93,0.83

In [ ]:
from sklearn.ensemble import RandomForestClassifier
regressor_model = RandomForestClassifier()
regressor_model.fit(train_x,train_y)

RandomForestClassifier()

In [ ]:
predictions = regressor_model.predict(test_x)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(test_y, predictions)

0.9518459069020867